//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _17thn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.Rental = new HashSet<Rental>();
        }
    
        public int id_car { get; set; }
        public Nullable<int> id_car_model { get; set; }
        public Nullable<int> id_color { get; set; }
        public string year_of_release { get; set; }
        public string state_number { get; set; }
        public string insurance_cost { get; set; }
        public string insurance_premium { get; set; }
        public string one_day_rental { get; set; }
    
        public virtual CarColor CarColor { get; set; }
        public virtual CarModel CarModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rental> Rental { get; set; }
    }
}
