//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _17thn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        public int id_rental { get; set; }
        public Nullable<int> id_client { get; set; }
        public Nullable<int> id_car { get; set; }
        public Nullable<System.DateTime> rental_start_date { get; set; }
        public string number_of_rental_days { get; set; }
        public string rental_price { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Client Client { get; set; }
    }
}
